/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matrice;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Leonardo Lionel
 */
public class GrafickoSucelje extends javax.swing.JFrame {

    /**
     * Creates new form GrafickoSucelje
     */
    public GrafickoSucelje() {
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        FileChooser.setFileFilter(filter);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldUnosDatoteke = new javax.swing.JTextField();
        jTextFieldUnosMatrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonUcitajDatoteku = new javax.swing.JButton();
        jButtonUcitajMatricu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUnosDatoteke.setName("jTextFieldUnosDatoteke"); // NOI18N
        jTextFieldUnosDatoteke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUnosDatotekeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUnosDatoteke, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, -1));
        jPanel1.add(jTextFieldUnosMatrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 70, -1));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jButtonUcitajDatoteku.setText("Učitaj datoteku");
        jButtonUcitajDatoteku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUcitajDatotekuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUcitajDatoteku, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jButtonUcitajMatricu.setText("Učitaj matricu");
        jButtonUcitajMatricu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUcitajMatricuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUcitajMatricu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 270, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    // fja koja prima string u kojem je zapisan ili tekst datoteke ili unos iz tekst fielda
    //prebacuje dani string u odgovarajuce polje double[][]
    //provjerava je li dani tekst ispravnog formata
    private void raspakirajMatricu(String tekst) {
        
        //System.out.println("ucitano: " + tekst);
        tekst = tekst.strip();

        if (!tekst.endsWith("]") || !tekst.startsWith("[")) {
            System.out.println("nepravilno unesena matrica");
            return;
        }
        //micem [ s pocetka i ] s kraja, zatim uklanjam bjeline s pocetka i kraja
        tekst = tekst.substring(1, tekst.length()-1);
        tekst = tekst.strip();
        if (!tekst.endsWith("]") || !tekst.startsWith("[")) {
            System.out.println("nepravilno unesena matrica");
            return;
        }
        //System.out.println(tekst);
        
        String matrica[] = tekst.split(Pattern.quote("["));
        //for(int i = 1; i < matrica.length; i++)
        //    System.out.println("redak " + i + ": " + matrica[i]);


        //unesenaMatrica = new double[matrica.length][matrica[0].length()-2];
        //System.out.println("duljina prvog retka: " + matrica[0].length());
        //double unesenaMatrica[][] = new double[matrica[0].length()][matrica.length];
        int brojStupaca = matrica[1].split(",").length;
        if(brojStupaca== 0) {
            System.out.println("nepravilno unesena matrica");
            return;
        }
        unesenaMatrica = new double[matrica.length-1][brojStupaca];

        for(int i = 1; i < matrica.length; i++) {
            matrica[i] = matrica[i].strip();
            //System.out.println(matrica[i]);

            int duljina = matrica[i].length();
            int cijelaDuljina = matrica.length;
            
            if(i < matrica.length-1) {
                if(matrica[i].endsWith(",") && matrica[i].lastIndexOf("]") == matrica[i].length()-2)
                    matrica[i] = matrica[i].substring(0, duljina-2);
                else {
                    System.out.println("nepravilno unesena matrica");
                    return;
                }
            }
            else matrica[i] = matrica[i].substring(0, duljina-1);
            //System.out.println(matrica[i]);

            String redak[] = matrica[i].split(",");
            //System.out.println("duljina retka: " + redak.length);
            
            if(redak.length != brojStupaca) {
                System.out.println("nepravilno unesena matrica");
                return;
            }
            
            for(int j = 0; j < redak.length; j++) {
                //System.out.println(Double.parseDouble(redak[j]));
                if (!redak[j].matches("^(\\d+(\\.\\d+)?)$")) {
                    System.out.println("nepravilno unesena matrica");
                    return;
                }
                else
                    unesenaMatrica[i-1][j] = Double.parseDouble(redak[j]);
            }            
            //System.out.println();                              
        }
        /*
        for(int i = 0; i < unesenaMatrica.length; i++) {
            for(int j = 0; j < unesenaMatrica[i].length; j++)
                System.out.print(unesenaMatrica[i][j]+",");
            System.out.println();   
        }  
        */
        jTextArea1.setText("");
        String tekstTextArea = "";
        
        for(int i = 0; i < unesenaMatrica.length; i++) {
            tekstTextArea += "[";
            for(int j = 0; j < unesenaMatrica[0].length; j++) {
                tekstTextArea += String.valueOf(unesenaMatrica[i][j]);
                if(j < unesenaMatrica[0].length-1)
                    tekstTextArea += ", ";
            }
            tekstTextArea += "]\n";                              
        }
        
        jTextArea1.setText(tekstTextArea);
    }
    
    private void jTextFieldUnosDatotekeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUnosDatotekeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldUnosDatotekeActionPerformed
// pritiskom buttona se otvara dialog za odabit txt fajla u kojem je zapisana matrica
    private void jButtonUcitajDatotekuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUcitajDatotekuActionPerformed
        // TODO add your handling code here:
        int returnVal = FileChooser.showOpenDialog((Component)evt.getSource());
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = FileChooser.getSelectedFile();
            try {
                imeDatoteke = file.toString();
            } catch (Exception ex) {
                
            }
            //System.out.println(imeDatoteke);
            String cijelaDatoteka = "", linija = "";
            File input = new File(imeDatoteke);
            
            Path p = Paths.get(input.getAbsolutePath());
            try {
                BufferedReader citac = Files.newBufferedReader(p, StandardCharsets.UTF_8);
                while((linija = citac.readLine()) != null) {
                    cijelaDatoteka += linija;
                raspakirajMatricu(cijelaDatoteka);    
                }
            }
            catch (Exception ex) {
            }
                    
        }
        
    }//GEN-LAST:event_jButtonUcitajDatotekuActionPerformed

    private void jButtonUcitajMatricuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUcitajMatricuActionPerformed
        // TODO add your handling code here:
        raspakirajMatricu(jTextFieldUnosMatrice.getText());
        jTextFieldUnosMatrice.setText("");
    }//GEN-LAST:event_jButtonUcitajMatricuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrafickoSucelje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrafickoSucelje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrafickoSucelje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrafickoSucelje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrafickoSucelje().setVisible(true);
            }
        });
    }

    private JFileChooser FileChooser = new JFileChooser();
    String imeDatoteke = "";
    double unesenaMatrica[][];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUcitajDatoteku;
    private javax.swing.JButton jButtonUcitajMatricu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldUnosDatoteke;
    private javax.swing.JTextField jTextFieldUnosMatrice;
    // End of variables declaration//GEN-END:variables
}
